import { Order, Platform, Statut, Ramassage, Livraison, Remboursement, CommandeRetour } from '../types';

const generateRandomDate = (start: Date, end: Date): string => {
  return new Date(start.getTime() + Math.random() * (end.getTime() - start.getTime())).toISOString();
};

const startDate = new Date(2023, 0, 1);
const endDate = new Date();

export const mockOrders: Order[] = [
  { 
    id: 'SF1001', 
    date: generateRandomDate(startDate, endDate), 
    customerName: 'Alice Johnson', 
    customerPhone: '33612345678', 
    address: '123 Rue de Paris, 75001 Paris',
    price: 99.99, 
    product: 'Wireless Headphones', 
    statut: Statut.Confirme, 
    assignedUserId: 'admin-001',
    noteClient: 'Appeler avant de livrer',
    ramassage: Ramassage.Ramasser,
    livraison: Livraison.Livre,
    remboursement: Remboursement.Payer,
    commandeRetour: CommandeRetour.NonRetourne,
    noteObligatoire: '',
    platform: Platform.Shopify,
    callCount: 2,
    deliveryCompanyId: null,
  },
  { 
    id: 'WC2001', 
    date: generateRandomDate(startDate, endDate), 
    customerName: 'Bob Smith', 
    customerPhone: '33787654321', 
    address: '45 Avenue de Lyon, 69002 Lyon',
    price: 49.50, 
    product: 'Leather Wallet', 
    statut: Statut.PasDeReponse, 
    assignedUserId: null,
    noteClient: '',
    ramassage: Ramassage.NonRamasser,
    livraison: Livraison.PasDeReponse,
    remboursement: Remboursement.NonPayer,
    commandeRetour: CommandeRetour.NonRetourne,
    noteObligatoire: 'Client difficile',
    platform: Platform.WooCommerce,
    callCount: 3,
    deliveryCompanyId: null,
  },
    { 
    id: 'SF1002', 
    date: generateRandomDate(startDate, endDate), 
    customerName: 'Charlie Brown', 
    customerPhone: '33698765432', 
    address: '78 Boulevard de Marseille, 13008 Marseille',
    price: 249.00, 
    product: 'Smartwatch', 
    statut: Statut.Rappel, 
    assignedUserId: 'admin-001',
    noteClient: 'Cadeau, emballage svp',
    ramassage: Ramassage.Ramasser,
    livraison: Livraison.PriseDeRdv,
    remboursement: Remboursement.Payer,
    commandeRetour: CommandeRetour.NonRetourne,
    noteObligatoire: '',
    platform: Platform.Shopify,
    callCount: 1,
    deliveryCompanyId: null,
  },
  { 
    id: 'WC2002', 
    date: generateRandomDate(startDate, endDate), 
    customerName: 'Diana Prince', 
    customerPhone: '33711223344', 
    address: '1 Rue de la Paix, 44000 Nantes',
    price: 99.99, 
    product: 'Wireless Headphones', 
    statut: Statut.Annule, 
    assignedUserId: null,
    noteClient: '',
    ramassage: Ramassage.NonRamasser,
    livraison: Livraison.Annule,
    remboursement: Remboursement.NonPayer,
    commandeRetour: CommandeRetour.Retourner,
    noteObligatoire: 'Stock insuffisant',
    platform: Platform.WooCommerce,
    callCount: 0,
    deliveryCompanyId: null,
  },
    { 
    id: 'SF1003', 
    date: generateRandomDate(startDate, endDate), 
    customerName: 'Ethan Hunt', 
    customerPhone: '33655667788', 
    address: '22 Place du Capitole, 31000 Toulouse',
    price: 78.25, 
    product: 'Coffee Maker', 
    statut: Statut.Confirme, 
    assignedUserId: 'admin-001',
    noteClient: '',
    ramassage: Ramassage.Ramasser,
    livraison: Livraison.Livre,
    remboursement: Remboursement.Payer,
    commandeRetour: CommandeRetour.NonRetourne,
    noteObligatoire: '',
    platform: Platform.Shopify,
    callCount: 1,
    deliveryCompanyId: null,
  },
  { 
    id: 'WC2003', 
    date: generateRandomDate(startDate, endDate), 
    customerName: 'Fiona Glenanne', 
    customerPhone: '33799887766', 
    address: '5 Allée de la Robertsau, 67000 Strasbourg',
    price: 120.00, 
    product: 'Bookshelf', 
    statut: Statut.BoiteVocale, 
    assignedUserId: 'admin-001',
    noteClient: 'Rappeler demain matin',
    ramassage: Ramassage.NonRamasser,
    livraison: Livraison.Reporte,
    remboursement: Remboursement.NonPayer,
    commandeRetour: CommandeRetour.NonRetourne,
    noteObligatoire: '',
    platform: Platform.WooCommerce,
    callCount: 1,
    deliveryCompanyId: null,
  },
];